services:
  bincollections:
    env_file: "./bincollections.env"
    build: .
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${HOST_CREDENTIALS_DIRECTORY}
        target: /usr/src/app/Credentials
